### ISSUE TITLE
Create GUI for Upvotes/Downvotes Feature

### ISSUE THREAD

**Issue by sanerem** [sanerem/SRMapvoting#6]
Create list of maps using standard Gmod UI appearance, containing the number of up and downvotes and the ability to sort, to rank maps by votes.

**Comment by sanerem** [comment]
Additionally, a method of capturing images of the maps, to enhance the map-change screen

**Comment by DarkRedemption** [comment]
https://wiki.garrysmod.com/page/Derma_Basic_Guide

Also, you may want to consider an admin panel to change minplayers and maxplayers in-game.
